### PR TITLE
Brunch build

### PR DESCRIPTION
**Pull request by m4dz**
This PR replaces Gulp with Brunch. Just for you, @aenario :heart:.

### CODE REVIEW

**Comment by aenario** [comment]
Awesome. I will rebase dont worry. I also propose we remove the minification as it will be handled by each app build.

**Comment by m4dz** [comment]
> I also propose we remove the minification as it will be handled by each app build.

As you want, it'll simplify the process :wink:.

**Comment by frankrousseau** [comment]
@aenario @m4dz could you close or merge that PR?

**Comment by aenario** [comment]
Closing now, will take it back at some point

**Pull request closed without merging**
